title = "test website for ASA bros"
baseURL = "/hugo-website"
languageCode = "en-in"
theme = "gohugo-theme-ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.6
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need.lets see if its really the thing"
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = "Hyderabaditom"
  youtube = "https://www.youtube.com/channel/UCSpPTMM90FqzJmZhYwYBkHg/videos"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 4
